"""added a new table to the users

Revision ID: 8eb54a91d7a8
Revises: e41e361ad212
Create Date: 2024-04-25 00:12:45.133660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb54a91d7a8'
down_revision = 'e41e361ad212'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('s_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 's_active')
    # ### end Alembic commands ###
