"""added a new table to the users

Revision ID: c465744763b1
Revises: 8eb54a91d7a8
Create Date: 2024-04-25 00:13:20.835978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c465744763b1'
down_revision = '8eb54a91d7a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 's_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('s_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
